# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21d7663cef290b0fd7f1626d4f3cb40be64b2877efb3024a68f0be110f7d4642ee5148c01fa9190549155b4d84787bd6ae4fe2cac250d9519ecff65e3a8e31e1

test:
  secret_key_base: 0482016973a668abdb376892526e81a57b9128ddbcae13bd2aea8dcedba94532730596b806e6340622755dc0a1825f3ebd2f11457b6114063ea59392868909b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
